#@host=https://<functionapp>.azurewebsites.net

# To call in Azure you will need to set the key in the header
# key can be obtained by running: az functionapp keys list --name <FunctionAppName> --resource-group <ResourceGroupName> --query "masterKey"
# and setting the key in the header as follows:
# x-functions-key: <key>
# Warning: if key is set in this file, do not save and commit the file.  
# instead save this file to a secure location and use it as needed

@host=http://localhost:7071

### Import data in AI Search
POST {{host}}/api/ingest
Content-Type: application/json

{
  "Text": "Contoso support incident 3455 is about slow performance.",
  "Title": "Contoso3455"
}

### Ask question of imported data
POST {{host}}/api/ask
Content-Type: application/json

{
  "question": "What is support incident 3455 about?"
}